name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install python
        run: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          pyenv install 3.8.0

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
          chmod +x get-poetry.py
          python get-poetry.py --preview
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install python packages
        run: poetry install

      - name: Run tests
        run: poetry run python test.py
